-- alter table HEATMAPRESSOURCES_MEDICAL_PROFESSIONALS add column MP_CONTROL_CENTER_ID varchar(36) ^
-- update HEATMAPRESSOURCES_MEDICAL_PROFESSIONALS set MP_CONTROL_CENTER_ID = <default_value> ;
-- alter table HEATMAPRESSOURCES_MEDICAL_PROFESSIONALS alter column MP_CONTROL_CENTER_ID set not null ;
alter table HEATMAPRESSOURCES_MEDICAL_PROFESSIONALS add column MP_CONTROL_CENTER_ID varchar(36) not null ;
alter table HEATMAPRESSOURCES_MEDICAL_PROFESSIONALS add column MP_CERTIFICATION varchar(255) ^
update HEATMAPRESSOURCES_MEDICAL_PROFESSIONALS set MP_CERTIFICATION = '' where MP_CERTIFICATION is null ;
alter table HEATMAPRESSOURCES_MEDICAL_PROFESSIONALS alter column MP_CERTIFICATION set not null ;
