alter table HEATMAPRESSOURCES_ABOUT_TRACKING alter column TS_CONTACT_CONTACT_PHONE rename to TS_CONTACT_CONTACT_PHONE__U73761 ^
alter table HEATMAPRESSOURCES_ABOUT_TRACKING add column TS_CONTACT_PHONE varchar(255) ;
