alter table HEATMAPRESSOURCES_HOSPITAL_ROOM_FACILITIES add column HRF_LOCATION_TRACKING_SOURCE VARCHAR(100) ;
alter table HEATMAPRESSOURCES_HOSPITAL_ROOM_FACILITIES add column HRF_LOCATION_TRACKING VARCHAR(100) ;
