alter table HEATMAPRESSOURCES_USERS alter column USER_RIGHTS_SUBSTITUTION_ID rename to USER_RIGHTS_SUBSTITUTION_ID__U78792 ^
alter table HEATMAPRESSOURCES_USERS alter column USER_RIGHTS_SUBSTITUTION_ID__U78792 set null ;
alter table HEATMAPRESSOURCES_USERS alter column USER_RIGHTS_ROLE_ID rename to USER_RIGHTS_ROLE_ID__U73213 ^
alter table HEATMAPRESSOURCES_USERS alter column USER_RIGHTS_ROLE_ID__U73213 set null ;
alter table HEATMAPRESSOURCES_USERS alter column USER_RIGHTS_GROUP_ID rename to USER_RIGHTS_GROUP_ID__U47409 ^
alter table HEATMAPRESSOURCES_USERS alter column USER_RIGHTS_GROUP_ID__U47409 set null ;
alter table HEATMAPRESSOURCES_USERS add column USER_RIGHTS_ROLE varchar(255) ^
update HEATMAPRESSOURCES_USERS set USER_RIGHTS_ROLE = '' where USER_RIGHTS_ROLE is null ;
alter table HEATMAPRESSOURCES_USERS alter column USER_RIGHTS_ROLE set not null ;
alter table HEATMAPRESSOURCES_USERS add column USER_RIGHTS_GROUP varchar(255) ;
alter table HEATMAPRESSOURCES_USERS add column USER_RIGHTS_SUBSTITUTION varchar(255) ^
update HEATMAPRESSOURCES_USERS set USER_RIGHTS_SUBSTITUTION = '' where USER_RIGHTS_SUBSTITUTION is null ;
alter table HEATMAPRESSOURCES_USERS alter column USER_RIGHTS_SUBSTITUTION set not null ;
update HEATMAPRESSOURCES_USERS set LAST_NAME = '' where LAST_NAME is null ;
alter table HEATMAPRESSOURCES_USERS alter column LAST_NAME set not null ;
