alter table HEATMAPRESSOURCES_USERS drop column USER_RIGHTS_GROUP_ID__U47409 cascade ;
alter table HEATMAPRESSOURCES_USERS drop column USER_RIGHTS_ROLE_ID__U73213 cascade ;
alter table HEATMAPRESSOURCES_USERS drop column USER_RIGHTS_SUBSTITUTION_ID__U78792 cascade ;
