-- alter table HEATMAPRESSOURCES_EMERGENCY_TRANSPORTATION add column ET_CONTROL_CENTER_ID varchar(36) ^
-- update HEATMAPRESSOURCES_EMERGENCY_TRANSPORTATION set ET_CONTROL_CENTER_ID = <default_value> ;
-- alter table HEATMAPRESSOURCES_EMERGENCY_TRANSPORTATION alter column ET_CONTROL_CENTER_ID set not null ;
alter table HEATMAPRESSOURCES_EMERGENCY_TRANSPORTATION add column ET_CONTROL_CENTER_ID varchar(36) not null ;
