-- alter table HEATMAPRESSOURCES_STATE_PROVINCE_DISTRICT add column SPD_EMERGENCY_CONTACT_ID varchar(36) ^
-- update HEATMAPRESSOURCES_STATE_PROVINCE_DISTRICT set SPD_EMERGENCY_CONTACT_ID = <default_value> ;
-- alter table HEATMAPRESSOURCES_STATE_PROVINCE_DISTRICT alter column SPD_EMERGENCY_CONTACT_ID set not null ;
alter table HEATMAPRESSOURCES_STATE_PROVINCE_DISTRICT add column SPD_EMERGENCY_CONTACT_ID varchar(36) not null ;
